/*----- PROTECTED REGION ID(TestCppTango1022StateMachine.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        TestCppTango1022StateMachine.cpp
//
// description : State machine file for the TestCppTango1022 class
//
//
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
// Copyright (C): 2022
//                European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                France
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "TestCppTango1022.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	TestCppTango1022::TestCppTango1022StateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  


namespace TestCppTango1022_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : TestCppTango1022::is_DoubleAttr_allowed()
 * Description:  Execution allowed for DoubleAttr attribute
 */
//--------------------------------------------------------
bool TestCppTango1022::is_DoubleAttr_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for DoubleAttr attribute in Write access.
	/*----- PROTECTED REGION ID(TestCppTango1022::DoubleAttrStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	TestCppTango1022::DoubleAttrStateAllowed_WRITE

	//	Not any excluded states for DoubleAttr attribute in read access.
	/*----- PROTECTED REGION ID(TestCppTango1022::DoubleAttrStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	TestCppTango1022::DoubleAttrStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(TestCppTango1022::TestCppTango1022StateAllowed.AdditionalMethods) ENABLED START -----*/
/* clang-format on */
//	Additional Methods
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	TestCppTango1022::TestCppTango1022StateAllowed.AdditionalMethods

}	//	End of namespace
