// NOLINTBEGIN(*)

/*----- PROTECTED REGION ID(FwdTestStateMachine.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        FwdTestStateMachine.cpp
//
// description : State machine file for the FwdTest class
//
// project :
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "FwdTest.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	FwdTest::FwdTestStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace FwdTest_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(FwdTest::FwdTestStateAllowed.AdditionalMethods) ENABLED START -----*/
/* clang-format on */
//	Additional Methods
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	FwdTest::FwdTestStateAllowed.AdditionalMethods

}	//	End of namespace

 // NOLINTEND(*)
