variables: &variables
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  # Build parameters. We later override them at job level if needed.
  CMAKE_DISABLE_PRECOMPILE_HEADERS: "OFF"
  CMAKE_BUILD_TYPE: "Debug"
  TANGO_USE_JPEG: "ON"
  BUILD_SHARED_LIBS: "ON"
  TANGO_USE_LIBCPP: "OFF"
  TOOLCHAIN_FILE: ""
  CTEST_PARALLEL_LEVEL: "1"
  BUILD_TESTING: "ON"

# See: https://docs.gitlab.com/ce/ci/yaml/README.html#workflowrules-templates
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pre-commit:
  image: registry.gitlab.com/tango-controls/docker/pre-commit:3.0.0
  services: []
  tags:
    - docker, linux, amd64
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure
  cache:
    paths:
      - ${PRE_COMMIT_HOME}

code-format:
  image: registry.gitlab.com/tango-controls/docker/ci/cpptango/llvm-latest:v3
  services: []
  tags:
    - docker, linux, amd64
  variables:
    PATCH_FILE: clang-format.patch
    TANGO_CLANG_FORMAT: "ON"
    TANGO_MAKE_TARGET: "clang-format"
  script:
    - git config --global --add safe.directory '*'
    - ci/config.sh
    - ci/build.sh
    - git diff > ${PATCH_FILE}
      # fail job if the patch file is not empty
    - '! test -s ${PATCH_FILE}'
  artifacts:
    when: always
    paths:
      - ${PATCH_FILE}

.job-template-no-test-run: &job-template-no-test-run
  image: registry.gitlab.com/tango-controls/docker/ci/cpptango/${OS_TYPE}
  services: []
  tags:
    - docker, linux, amd64
  needs:
    - pre-commit
    - code-format
  script:
    - ci/config.sh
    - ci/build.sh

.job-template-with-tests: &job-template-with-tests
  image: registry.gitlab.com/tango-controls/docker/ci/cpptango/${OS_TYPE}
  services:
    - docker:20.10.16-dind
  tags:
    - dind, skao, docker, linux, amd64
  needs:
    - pre-commit
    - code-format
  script:
    - ci/config.sh
    - ci/build.sh
    - ci/test.sh
  after_script:
    - ci/print_coredumps.sh
    - mkdir -p build/tests/results
  artifacts:
    when: always
    paths:
      - build/tests/results
      - build/tests/core.*

abi-api-compliance-check:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: gcc-latest:v2
    GIT_COMMITTER_NAME: "$GITLAB_USER_NAME"
    GIT_COMMITTER_EMAIL: "$GITLAB_USER_EMAIL"
    CI_TARGET_BRANCH: "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
    GIT_STRATEGY: "none"
  rules:
    # This job runs only for merge requests.
    - if: $CI_MERGE_REQUEST_IID
  # allow failures for next release cycle which is allowed to break ABI
  allow_failure: true
  script: # override
    - git clone -b ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} ${CI_PROJECT_URL} src
    - cd src
    - ci/check-ABI-API-compliance.sh
  artifacts:
    when: always
    paths:
      - compat_reports

llvm-latest:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: llvm-latest:v2
    TANGO_WARNINGS_AS_ERRORS: "ON"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"

gcc-latest:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: gcc-latest:v2
    TANGO_WARNINGS_AS_ERRORS: "ON"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"

ubuntu-20.04:
  <<: *job-template-with-tests
  variables:
    <<: *variables
    OS_TYPE: ubuntu-20.04:v2

coverage:
  <<: *job-template-with-tests
  variables:
    <<: *variables
    TANGO_ENABLE_COVERAGE: "ON"
    OS_TYPE: debian12:v2
  after_script:
    - mkdir -p build/tests/results
    - mkdir coverage
    - >
        gcovr --filter '^src/' --filter '^log4tango/(?!tests/)' -j$(nproc)
        --xml --output coverage.xml
    - >
        gcovr --filter '^src/' --filter '^log4tango/(?!tests/)' -j$(nproc)
        --html-details --output coverage/coverage.html
    - >
        gcovr --filter '^src/' --filter '^log4tango/(?!tests/)' -j$(nproc)
    - tar czf coverage.tar.gz coverage
  artifacts:
    when: always
    reports:
      coverage_report:
        # coverage report provides line-by-line info
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - build/tests/results
      - build/tests/core.*
      - coverage.xml
      - coverage.tar.gz
  # keyword/regex to extract total coverage % for this CI job (which is also called "coverage")
  coverage: '/^TOTAL.*\s+(\d+\%)$/'

debian12-static:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian12:v2
    BUILD_SHARED_LIBS: "OFF"

debian12-no-pch:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian12:v2
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"

debian12-release:
  <<: *job-template-with-tests
  variables:
    <<: *variables
    OS_TYPE: debian12:v2
    CMAKE_BUILD_TYPE: Release

debian12:
  <<: *job-template-with-tests
  variables:
    <<: *variables
    OS_TYPE: debian12:v2

debian12-no-jpeg:
  <<: *job-template-with-tests
  variables:
    <<: *variables
    OS_TYPE: debian12:v2
    TANGO_USE_JPEG: "OFF"

debian12-cross-32bit:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian12-cross-32bit:v2
    CMAKE_BUILD_TYPE: "Debug"
    TOOLCHAIN_FILE: "configure/toolchain-i686.cmake"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"
    TANGO_WARNINGS_AS_ERRORS: "ON"
    TANGO_USE_JPEG: "OFF"

debian11:
  <<: *job-template-with-tests
  variables:
    <<: *variables
    OS_TYPE: debian11:v2

ubuntu-20.04-jpeg9:
  <<: *job-template-with-tests
  variables:
    <<: *variables
    OS_TYPE: ubuntu-20.04-jpeg9:v2

clang-analyzer:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: ubuntu-20.04:v2
    CMAKE_EXPORT_COMPILE_COMMANDS: "ON"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"
    BUILD_TESTING: "OFF"
    CMAKE_BUILD_TYPE: "Debug"
    TANGO_MAKE_TARGET: "idl_source"
    CC: /usr/lib/llvm-12/bin/clang
    CXX: /usr/lib/llvm-12/bin/clang++
  script: # override
    - sudo ln -s /usr/bin/clang-12 /usr/local/bin/clang
    - sudo ln -s /usr/bin/clang-extdef-mapping-12 /usr/local/bin/clang-extdef-mapping
    - ci/config.sh
    - ci/build.sh
    # scan-build command must be wrapped in quotes because
    # --analyzer-config option cannot contain whitespaces.
    - "/usr/share/clang/scan-build-py-12/bin/analyze-build                          \
      -v                                                                            \
      --cdb build/compile_commands.json                                             \
      --exclude build/cppapi/server/idl                                             \
      --keep-empty                                                                  \
      --output clang-analyzer-results                                               \
      --force-analyze-debug-code                                                    \
      --analyzer-config                                                             \
        stable-report-filename=true,aggressive-binary-operation-simplification=true \
      --enable-checker core                                                         \
      --enable-checker cplusplus                                                    \
      --enable-checker deadcode                                                     \
      --enable-checker nullability                                                  \
      --enable-checker optin.cplusplus                                              \
      --enable-checker optin.performance                                            \
      --enable-checker optin.portability                                            \
      --enable-checker security                                                     \
      --enable-checker unix                                                         \
      --enable-checker alpha.clone                                                  \
      --enable-checker alpha.core                                                   \
      --enable-checker alpha.cplusplus                                              \
      --enable-checker alpha.deadcode                                               \
      --enable-checker alpha.nondeterminism                                         \
      --enable-checker alpha.unix                                                   \
      > clang-analyzer-output.txt"
  artifacts:
    when: always
    paths:
      - clang-analyzer-output.txt
      - clang-analyzer-results

clang-tidy:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: ubuntu-20.04:v2
    CMAKE_EXPORT_COMPILE_COMMANDS: "ON"
    CMAKE_UNITY_BUILD: "ON"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"
    BUILD_TESTING: "OFF"
    CMAKE_BUILD_TYPE: "Debug"
    TANGO_MAKE_TARGET: "idl_source"
    CC: /usr/lib/llvm-12/bin/clang
    CXX: /usr/lib/llvm-12/bin/clang++
  script: # override
    # Install codeclimate. This is needed for generating HTML report.
    - ci/config.sh
    - ci/build.sh
    - >
      run-clang-tidy-12
      -p build -header-filter='.*' 'cppapi/(?!server/idl)' 'log4tango/src'
      | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' > clang-tidy-output.txt
    # Print warning summary (check name and occurrence count).
    - >
      grep -E 'warning: .+ \[.+\]$' clang-tidy-output.txt
      | sort | uniq | sed -E 's|^.+ \[(.+)\]|\1|' | sort | uniq -c
    # Produce a report in Code Climate JSON format.
    - >
      cat clang-tidy-output.txt
      | ./ci/clang-tidy-to-code-climate.py "$(pwd)/"
      > code-quality-report.json
    # Produce a report in HTML format.
    - >
      cat code-quality-report.json
      | ruby -I/home/tango/dependencies/codeclimate/lib ci/code-climate-json-to-html.rb "$(pwd)"
      > code-quality-report.html
  artifacts:
    when: always
    reports:
       codequality: code-quality-report.json
    paths:
      - clang-tidy-output.txt
      - code-quality-report.json
      - code-quality-report.html

# job to build against custom library locations and minimum supported versions of dependent libraries
# using TANGO_XXX_BASE
cmake-with-locations-and-min-versions-BASE:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian-minimum-versions:v2
  parallel:
    matrix:
      - BUILD_TYPE: [Release, Debug, RelWithDebInfo, MinSizeRel]
  script:
    # needs to be in-sync with scripts.git/install_minimum_versions.sh
    - INSTALL_PREFIX=/tmp/install
    - export PATH=${PATH}:${INSTALL_PREFIX}/cmake/bin
    - >
      cmake
      -Werror=dev
      -B build
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -DTANGO_CPPZMQ_BASE=${INSTALL_PREFIX}/cppzmq
      -DTANGO_IDL_BASE=${INSTALL_PREFIX}/tango-idl
      -DTANGO_OMNI_BASE=${INSTALL_PREFIX}/omniORB
      -DTANGO_ZMQ_BASE=${INSTALL_PREFIX}/libzmq
      -DTANGO_JPEG_BASE=${INSTALL_PREFIX}/libjpeg
    - ci/build.sh

# and pkg-config
cmake-with-locations-and-min-versions-PKGCONFIG:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian-minimum-versions:v2
  parallel:
    matrix:
      - BUILD_TYPE: [Release, Debug, RelWithDebInfo, MinSizeRel]
  script:
    # needs to be in-sync with scripts.git/install_minimum_versions.sh
    - INSTALL_PREFIX=/tmp/install
    - export PATH=${PATH}:${INSTALL_PREFIX}/cmake/bin
    - export PKG_CONFIG_PATH="${INSTALL_PREFIX}/omniORB/lib/pkgconfig:${INSTALL_PREFIX}/libjpeg/lib/pkgconfig:${INSTALL_PREFIX}/tango-idl/lib/pkgconfig:${INSTALL_PREFIX}/libzmq/lib/pkgconfig"
    - >
      cmake
      -Werror=dev
      -B build
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -DTANGO_CPPZMQ_BASE=${INSTALL_PREFIX}/cppzmq
    - ci/build.sh

debian-maximum-cmake:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian-maximum-cmake:v1

alpine:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: alpine-3.15:v2

doxygen-documentation:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian12:v2
    TANGO_USE_JPEG: "OFF"
    BUILD_TESTING: "OFF"
    TANGO_MAKE_TARGET: "doc"
  artifacts:
    when: always
    paths:
      - build/doc_html

sanitizer:
  <<: *job-template-with-tests
  variables:
    <<: *variables
    OS_TYPE: ubuntu-20.04:v2
    CC: /usr/lib/llvm-12/bin/clang
    CXX: /usr/lib/llvm-12/bin/clang++
    ASAN_OPTIONS: detect_stack_use_after_return=1
    TSAN_OPTIONS: second_deadlock_stack=1
    UBSAN_OPTIONS: "\
      print_stacktrace=1,\
      report_error_type=1,\
      halt_on_error=1,\
      suppressions=$CI_PROJECT_DIR/tests/suppressions-ubsan.supp"
    SKIP_TESTS: "(event::per_event|old_tests::ring_depth)"
  # Failures are temporarily allowed until sanitizer issues are fixed.
  allow_failure: true
  # Increase timeout, this is required by UBSAN job.
  timeout: 2h
  parallel:
    matrix:
      - TANGO_ENABLE_SANITIZER: [ASAN, TSAN, UBSAN]
  rules:
    - if: '$CI_JOB_NAME == "tango_enable_sanitizer: [UBSAN]"'
      allow_failure: false
      when: on_success
    - when: on_success

# Trigger conda dev package build for the default branch
build-conda-dev-package:
  stage: test
  variables:
    DEPLOY_PACKAGE: "true"
  trigger:
    project: tango-controls/conda/cpptango-feedstock
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

libcpp:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: llvm-latest:v2
    TANGO_WARNINGS_AS_ERRORS: "ON"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"
    TANGO_USE_LIBCPP: "ON"

pkgconfig-fedora37:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: fedora37:v2
    TANGO_USE_JPEG: "OFF"
    BUILD_TESTING: "OFF"
  script: # override
    - ci/config.sh
    - ci/run-pkg-config-validation.sh

cmake-superproject:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian12:v2
  script: # override
    - cd tests/superproject
    - ../../ci/config.sh
    - ../../ci/build.sh
