variables: &variables
  DEBIAN_FRONTEND: noninteractive
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  # Build parameters. We later override them at job level if needed.
  RUN_TESTS: "ON"
  STOCK_CPPZMQ: "ON"
  STOCK_OMNIORB: "ON"
  CMAKE_DISABLE_PRECOMPILE_HEADERS: "OFF"
  CMAKE_BUILD_TYPE: "Debug"
  TANGO_USE_JPEG: "ON"
  BUILD_SHARED_LIBS: "ON"
  TANGO_USE_LIBCPP: "OFF"
  TOOLCHAIN_FILE: ""
  JPEG_LIB: libjpeg-dev
  TANGO_IDL_TAG: "5.1.2"
  CTEST_PARALLEL_LEVEL: "1"
  BUILD_TESTING: "ON"

services:
  - docker:20.10.16-dind

# See: https://docs.gitlab.com/ce/ci/yaml/README.html#workflowrules-templates
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.job-template: &job-template
  image: debian:10
  tags:
    - dind, skao, docker, linux, amd64
  before_script:
    - ulimit -c unlimited
    - echo "core.%e.%p.%t" > /proc/sys/kernel/core_pattern
    - apt-get update && apt-get install -y git wget unzip docker.io
    - ci/before_install.sh
    - docker build --build-arg JPEG_LIB=${JPEG_LIB} -t cpp_tango ci/${OS_TYPE}
    - >
        docker run
        --rm
        --name cpp_tango
        --user root
        --ulimit core=-1
        -e TANGO_HOST=${TANGO_HOST}
        -e TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
        -e DOCKER_HOST=tcp://$(getent hosts docker | awk '{ print $1 }'):2375
        -v `pwd`:/home/tango/src
        -v `pwd`/idl:/home/tango/idl
        -v `pwd`/cppzmq:/home/tango/cppzmq
        -v `pwd`/omniorb:/home/tango/omniorb
        -v `pwd`/build-wrapper-linux-x86:/home/tango/build-wrapper-linux-x86
        -dit
        cpp_tango
    - ci/install_tango_idl.sh
    - if [ ${STOCK_CPPZMQ} = "OFF" ]; then ci/install_cppzmq.sh; fi
    - if [ ${STOCK_OMNIORB} = "OFF" ]; then ci/install_omniorb.sh; fi
  script:
    - ci/run.sh
    - ci/test-docker-exec.sh
  after_script:
    - ci/print_coredumps.sh
    - docker stop cpp_tango || true
    - mkdir -p build/tests/results
  artifacts:
    when: always
    paths:
      - build/tests/results
      - build/tests/core.*

.job-template-no-test-run: &job-template-no-test-run
  image: registry.gitlab.com/tango-controls/docker/ci/cpptango/${OS_TYPE}
  services: []
  tags:
    - docker, linux, amd64
  script:
    - ci/config.sh
    - ci/build.sh

.job-template-with-tests: &job-template-with-tests
  image: registry.gitlab.com/tango-controls/docker/ci/cpptango/${OS_TYPE}
  services:
    - docker:20.10.16-dind
  tags:
    - dind, skao, docker, linux, amd64
  script:
    - ci/config.sh
    - ci/build.sh
    - ci/test.sh
  after_script:
    - # ci/print_coredumps.sh # disable for now until the porting is finished
    - mkdir -p build/tests/results
  artifacts:
    when: always
    paths:
      - build/tests/results
      - build/tests/core.*

abi-api-compliance-check:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: gcc-latest:v1
    GIT_COMMITTER_NAME: "$GITLAB_USER_NAME"
    GIT_COMMITTER_EMAIL: "$GITLAB_USER_EMAIL"
    CI_TARGET_BRANCH: "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
    GIT_STRATEGY: "none"
  rules:
    # This job runs only for merge requests.
    - if: $CI_MERGE_REQUEST_IID
  # allow failures for next release cycle which is allowed to break ABI
  allow_failure: true
  script: # override
    - git clone -b ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} ${CI_PROJECT_URL} src
    - cd src
    - ci/check-ABI-API-compliance.sh
  artifacts:
    when: always
    paths:
      - compat_reports

llvm-latest:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: llvm-latest:v1
    TANGO_WARNINGS_AS_ERRORS: "ON"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"

gcc-latest:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: gcc-latest:v1
    TANGO_WARNINGS_AS_ERRORS: "ON"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"

ubuntu-20.04:
  <<: *job-template-with-tests
  variables:
    <<: *variables
    OS_TYPE: ubuntu-20.04:v1

coverage:
  <<: *job-template
  variables:
    <<: *variables
    TANGO_ENABLE_COVERAGE: "ON"
    OS_TYPE: debian10
    STOCK_CPPZMQ: "OFF"
  after_script:
    - mkdir -p build/tests/results
    - mkdir coverage
    - >
        docker exec --workdir /home/tango/src cpp_tango
        gcovr --filter '^cppapi/' --filter '^log4tango/(?!tests/)' -j$(nproc)
        --xml --output coverage.xml
    - >
        docker exec --workdir /home/tango/src cpp_tango
        gcovr --filter '^cppapi/' --filter '^log4tango/(?!tests/)' -j$(nproc)
        --html-details --output coverage/coverage.html
    - >
        docker exec --workdir /home/tango/src cpp_tango
        gcovr --filter '^cppapi/' --filter '^log4tango/(?!tests/)' -j$(nproc)
    - tar czf coverage.tar.gz coverage
    - docker stop cpp_tango
  artifacts:
    when: always
    reports:
      coverage_report:
        # coverage report provides line-by-line info
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - build/tests/results
      - build/tests/core.*
      - coverage.xml
      - coverage.tar.gz
  # keyword/regex to extract total coverage % for this CI job (which is also called "coverage")
  coverage: '/^TOTAL.*\s+(\d+\%)$/'

debian12-static:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian12:v1
    BUILD_SHARED_LIBS: "OFF"

debian12-no-pch:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian12:v1
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"

debian11-release:
  <<: *job-template
  variables:
    <<: *variables
    OS_TYPE: debian11
    CMAKE_BUILD_TYPE: Release
    STOCK_CPPZMQ: "OFF"

debian11:
  <<: *job-template
  variables:
    <<: *variables
    OS_TYPE: debian11
    STOCK_CPPZMQ: "OFF"

debian11-no-jpeg:
  <<: *job-template
  variables:
    <<: *variables
    OS_TYPE: debian11
    STOCK_CPPZMQ: "OFF"
    TANGO_USE_JPEG: "OFF"

debian12-cross-32bit:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian12-cross-32bit:v1
    CMAKE_BUILD_TYPE: "Debug"
    TOOLCHAIN_FILE: "configure/toolchain-i686.cmake"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"
    TANGO_WARNINGS_AS_ERRORS: "ON"
    TANGO_USE_JPEG: "OFF"

debian10:
  <<: *job-template
  variables:
    <<: *variables
    OS_TYPE: debian10
    STOCK_CPPZMQ: "OFF"

ubuntu-20.04-jpeg9:
  <<: *job-template
  variables:
    <<: *variables
    OS_TYPE: ubuntu-20.04
    STOCK_CPPZMQ: "OFF"
    JPEG_LIB: libjpeg9-dev

clang-analyzer:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: ubuntu-20.04:v1
    CMAKE_EXPORT_COMPILE_COMMANDS: "ON"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"
    BUILD_TESTING: "OFF"
    CMAKE_BUILD_TYPE: "Debug"
    TANGO_MAKE_TARGET: "idl_source"
    CC: /usr/lib/llvm-12/bin/clang
    CXX: /usr/lib/llvm-12/bin/clang++
  script: # override
    - sudo ln -s /usr/bin/clang-12 /usr/local/bin/clang
    - sudo ln -s /usr/bin/clang-extdef-mapping-12 /usr/local/bin/clang-extdef-mapping
    - ci/config.sh
    - ci/build.sh
    # scan-build command must be wrapped in quotes because
    # --analyzer-config option cannot contain whitespaces.
    - "/usr/share/clang/scan-build-py-12/bin/analyze-build                          \
      -v                                                                            \
      --cdb build/compile_commands.json                                             \
      --exclude build/cppapi/server/idl                                             \
      --keep-empty                                                                  \
      --output clang-analyzer-results                                               \
      --force-analyze-debug-code                                                    \
      --analyzer-config                                                             \
        stable-report-filename=true,aggressive-binary-operation-simplification=true \
      --enable-checker core                                                         \
      --enable-checker cplusplus                                                    \
      --enable-checker deadcode                                                     \
      --enable-checker nullability                                                  \
      --enable-checker optin.cplusplus                                              \
      --enable-checker optin.performance                                            \
      --enable-checker optin.portability                                            \
      --enable-checker security                                                     \
      --enable-checker unix                                                         \
      --enable-checker alpha.clone                                                  \
      --enable-checker alpha.core                                                   \
      --enable-checker alpha.cplusplus                                              \
      --enable-checker alpha.deadcode                                               \
      --enable-checker alpha.nondeterminism                                         \
      --enable-checker alpha.unix                                                   \
      > clang-analyzer-output.txt"
  artifacts:
    when: always
    paths:
      - clang-analyzer-output.txt
      - clang-analyzer-results

clang-tidy:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: ubuntu-20.04:v1
    CMAKE_EXPORT_COMPILE_COMMANDS: "ON"
    CMAKE_UNITY_BUILD: "ON"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"
    BUILD_TESTING: "OFF"
    CMAKE_BUILD_TYPE: "Debug"
    TANGO_MAKE_TARGET: "idl_source"
    CC: /usr/lib/llvm-12/bin/clang
    CXX: /usr/lib/llvm-12/bin/clang++
  script: # override
    # Install codeclimate. This is needed for generating HTML report.
    - ci/config.sh
    - ci/build.sh
    - >
      run-clang-tidy-12
      -p build -header-filter='.*' 'cppapi/(?!server/idl)' 'log4tango/src'
      | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' > clang-tidy-output.txt
    # Print warning summary (check name and occurrence count).
    - >
      grep -E 'warning: .+ \[.+\]$' clang-tidy-output.txt
      | sort | uniq | sed -E 's|^.+ \[(.+)\]|\1|' | sort | uniq -c
    # Produce a report in Code Climate JSON format.
    - >
      cat clang-tidy-output.txt
      | ./ci/clang-tidy-to-code-climate.py "$(pwd)/"
      > code-quality-report.json
    # Produce a report in HTML format.
    - >
      cat code-quality-report.json
      | ruby -I/home/tango/dependencies/codeclimate/lib ci/code-climate-json-to-html.rb "$(pwd)"
      > code-quality-report.html
  artifacts:
    when: always
    reports:
       codequality: code-quality-report.json
    paths:
      - clang-tidy-output.txt
      - code-quality-report.json
      - code-quality-report.html

# job to build against custom library locations and minimum supported versions of dependent libraries
# using TANGO_XXX_BASE
cmake-with-locations-and-min-versions-BASE:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian-minimum-versions:v1
  parallel:
    matrix:
      - BUILD_TYPE: [Release , Debug, RelWithDebInfo, MinSizeRel]
  script:
    # needs to be in-sync with scripts.git/install_minimum_versions.sh
    - INSTALL_PREFIX=/tmp/install
    - export PATH=${PATH}:${INSTALL_PREFIX}/cmake/bin
    - >
      cmake
      -Werror=dev
      -B build
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -DTANGO_CPPZMQ_BASE=${INSTALL_PREFIX}/cppzmq
      -DTANGO_IDL_BASE=${INSTALL_PREFIX}/tango-idl
      -DTANGO_OMNI_BASE=${INSTALL_PREFIX}/omniORB
      -DTANGO_ZMQ_BASE=${INSTALL_PREFIX}/libzmq
      -DTANGO_JPEG_BASE=${INSTALL_PREFIX}/libjpeg
    - ci/build.sh

# and pkg-config
cmake-with-locations-and-min-versions-PKGCONFIG:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian-minimum-versions:v1
  parallel:
    matrix:
      - BUILD_TYPE: [Release , Debug, RelWithDebInfo, MinSizeRel]
  script:
    # needs to be in-sync with scripts.git/install_minimum_versions.sh
    - INSTALL_PREFIX=/tmp/install
    - export PATH=${PATH}:${INSTALL_PREFIX}/cmake/bin
    - export PKG_CONFIG_PATH="${INSTALL_PREFIX}/omniORB/lib/pkgconfig:${INSTALL_PREFIX}/libjpeg/lib/pkgconfig:${INSTALL_PREFIX}/tango-idl/lib/pkgconfig:${INSTALL_PREFIX}/libzmq/lib/pkgconfig"
    - >
      cmake
      -Werror=dev
      -B build
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -DTANGO_CPPZMQ_BASE=${INSTALL_PREFIX}/cppzmq
    - ci/build.sh

alpine:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: alpine-3.15:v1

doxygen-documentation:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian12:v1
    TANGO_USE_JPEG: "OFF"
    BUILD_TESTING: "OFF"
    TANGO_MAKE_TARGET: "doc"
  artifacts:
    when: always
    paths:
      - build/doc_html

sanitizer:
  <<: *job-template
  # Failures are temporarily allowed until sanitizer issues are fixed.
  allow_failure: true
  image: ubuntu:focal
  tags:
    - dind, skao, docker, linux, amd64
  variables:
    <<: *variables
    CC: /usr/lib/llvm-12/bin/clang
    CXX: /usr/lib/llvm-12/bin/clang++
    ASAN_OPTIONS: detect_stack_use_after_return=1
    TSAN_OPTIONS: second_deadlock_stack=1
    UBSAN_OPTIONS: "\
      print_stacktrace=1,\
      report_error_type=1,\
      halt_on_error=1,\
      suppressions=$CI_PROJECT_DIR/tests/suppressions-ubsan.supp"
  # Increase timeout, this is required by UBSAN job.
  timeout: 2h
  parallel:
    matrix:
      - SANITIZER: [ASAN, TSAN, UBSAN]
  rules:
    - if: '$CI_JOB_NAME == "sanitizer: [UBSAN]"'
      allow_failure: false
      when: on_success
    - when: on_success
  before_script:
    - ulimit -c unlimited
    - echo "core.%e.%p.%t" > /proc/sys/kernel/core_pattern
    - echo "1" > /proc/sys/net/ipv4/ip_forward
    - apt-get update
    # add kitware repository for cmake
    - apt-get install -y ca-certificates gpg wget
    - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null
      | gpg --dearmor -
      | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
    - echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main'
      | tee /etc/apt/sources.list.d/kitware.list >/dev/null
    - apt-get update
    - >
      apt-get install -y
      clang-12
      cmake
      docker.io
      gdb
      git
      iproute2
      libcos4-dev
      libomniorb4-dev
      libomnithread4-dev
      libzmq3-dev
      omniidl
      python3-minimal
      libjpeg-dev
    # Setup a route to the containers running inside dind.
    - >
      ip route add
      $(docker network inspect -f '{{(index .IPAM.Config 0).Subnet}}' bridge)
      via
      $(getent hosts docker | awk '{ print $1 }')
      dev eth0
    # Symbolizer is required for sanitizers.
    - ln -s /usr/lib/llvm-12/bin/llvm-symbolizer /usr/local/bin
    # Install tango-idl
    - git clone -b $TANGO_IDL_TAG --depth 1 https://gitlab.com/tango-controls/tango-idl.git /idl
    - cmake -B /idl/build /idl
    - make -C /idl/build install
    # Install cppzmq
    - git clone -b v4.7.1 --depth 1 https://github.com/zeromq/cppzmq.git /cppzmq
    - cmake -B /cppzmq/build -DCPPZMQ_BUILD_TESTS=OFF /cppzmq
    - make -C /cppzmq/build install
    # Create build directory for cppTango.
    - mkdir build
  script:
    - cd build
    - >
      cmake ..
      -Werror=dev
      -DCMAKE_BUILD_TYPE=Debug
      -DBUILD_TESTING=ON
      -DCMAKE_DISABLE_PRECOMPILE_HEADERS=OFF
      -DTANGO_ENABLE_SANITIZER=$SANITIZER
    - make
    - docker pull registry.gitlab.com/tango-controls/docker/mysql:5.16-mysql-5
    - docker pull registry.gitlab.com/tango-controls/docker/tango-db:5.16
    - ctest -j$(nproc) -E '(event::per_event|old_tests::ring_depth)' --output-on-failure

# Trigger conda dev package build for the default branch
build-conda-dev-package:
  stage: test
  variables:
    DEPLOY_PACKAGE: "true"
  trigger:
    project: tango-controls/conda/cpptango-feedstock
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

libcpp:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: llvm-latest:v1
    TANGO_WARNINGS_AS_ERRORS: "ON"
    CMAKE_DISABLE_PRECOMPILE_HEADERS: "ON"
    TANGO_USE_LIBCPP: "ON"

pkgconfig-fedora37:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: fedora37:v1
    TANGO_USE_JPEG: "OFF"
    BUILD_TESTING: "OFF"
    # NOTE: Below we are lying to cmake about the OMNIORB_VERSION because the
    # version provided by Fedora is unsupported, however, for this test we do not
    # want to run anything, so we don't care.
    OMNIORB_VERSION: "4.2.5"
  script: # override
    - ci/config.sh
    - ci/run-pkg-config-validation.sh

cmake-superproject:
  <<: *job-template-no-test-run
  variables:
    <<: *variables
    OS_TYPE: debian12:v1
  script: # override
    - cd tests/superproject
    - ../../ci/config.sh
    - ../../ci/build.sh
