version: 0.0.{build}
branches:
  only:
    - main

configuration:
  - Debug
  - Release

environment:
  # Common variables
  TANGO_IDL_BASE: C:\projects\tangoidl
  IDL_SOURCE: C:\projects\tangoidl-source
  JPEG_VERSION: 2.0.3
  TANGO_JPEG_BASE: C:/libjpeg-turbo
  NASM_VERSION: 2.15.05
  
  # Iteration order:
  # - VS Image (2017)
  # - Architecture (x86 aka win32 or x64)
  # - BUILD_SHARED_LIBS (ON or OFF)

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      ARCH: x64-msvc15
      VCPKG_DEFAULT_TRIPLET: x64-windows
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      PYTHONPATH: c:\Python37-x64\
      PYVER: "py37"
      TANGO_USE_PCH: ON
      TANGO_WARNINGS_AS_ERRORS: ON
      NASM_DOWNLOAD_LINK: "https://www.nasm.us/pub/nasm/releasebuilds/%NASM_VERSION%/win64/nasm-%NASM_VERSION%-installer-x64.exe"
      BUILD_SHARED_LIBS: ON
      CMAKE_CXX_FLAGS_RELEASE : "/MD"
      CMAKE_CXX_FLAGS_DEBUG : "/MDd"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      ARCH: x64-msvc15
      VCPKG_DEFAULT_TRIPLET: x64-windows
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      PYTHONPATH: c:\Python37-x64\
      PYVER: "py37"
      TANGO_USE_PCH: ON
      TANGO_WARNINGS_AS_ERRORS: ON
      NASM_DOWNLOAD_LINK: "https://www.nasm.us/pub/nasm/releasebuilds/%NASM_VERSION%/win64/nasm-%NASM_VERSION%-installer-x64.exe"
      BUILD_SHARED_LIBS: OFF
      CMAKE_CXX_FLAGS_RELEASE : "/MT"
      CMAKE_CXX_FLAGS_DEBUG : "/MTd"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: win32
      ARCH: win32-msvc15
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      PYTHONPATH: c:\Python37\
      PYVER: "py37"
      TANGO_USE_PCH: ON
      TANGO_WARNINGS_AS_ERRORS: OFF
      NASM_DOWNLOAD_LINK: "https://www.nasm.us/pub/nasm/releasebuilds/%NASM_VERSION%/win32/nasm-%NASM_VERSION%-installer-x86.exe"
      BUILD_SHARED_LIBS: ON
      CMAKE_CXX_FLAGS_RELEASE : "/MD"
      CMAKE_CXX_FLAGS_DEBUG : "/MDd"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: win32
      ARCH: win32-msvc15
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      PYTHONPATH: c:\Python37\
      PYVER: "py37"
      TANGO_USE_PCH: ON
      TANGO_WARNINGS_AS_ERRORS: OFF
      NASM_DOWNLOAD_LINK: "https://www.nasm.us/pub/nasm/releasebuilds/%NASM_VERSION%/win32/nasm-%NASM_VERSION%-installer-x86.exe"
      BUILD_SHARED_LIBS: OFF
      CMAKE_CXX_FLAGS_RELEASE : "/MT"
      CMAKE_CXX_FLAGS_DEBUG : "/MTd"

init:
  #RDP from start
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # Tango IDL
  - cmd: git clone --depth 1 --quiet https://gitlab.com/tango-controls/tango-idl %IDL_SOURCE%
  - cmd: cd "C:\projects\"
  # Zmq
  - cmd: cd "C:\projects\"
  - cmd: md zeromq
  - cmd: cd "C:\projects\"
  - appveyor DownloadFile https://github.com/tango-controls/zmq-windows-ci/releases/download/4.0.5-2/zmq-4.0.5-2_%ARCH%.zip
  - cmd: 7z -y x zmq-4.0.5-2_%ARCH%.zip -oC:\projects\zeromq\
  #- cmd: move C:\projects\zeromq\lib\Release\libzmq*mt-4*.lib C:\projects\zeromq\lib\Release\libzmq.lib
  # OmniOrb
  - cmd: cd "C:\projects\"
  - cmd: md omniorb
  - cmd: cd "C:\projects\"
  - appveyor DownloadFile https://github.com/tango-controls/omniorb-windows-ci/releases/download/4.2.5/omniorb-4.2.5_%ARCH%_%PYVER%.zip
  - cmd: 7z -y x omniorb-4.2.5_%ARCH%_%PYVER%.zip -oC:\projects\omniorb\
  #Pthread-Win32
  - cmd: cd "C:\projects\"
  - cmd: md pthreads-win32
  - cmd: cd "C:\projects\"
  - appveyor DownloadFile https://github.com/tango-controls/Pthread_WIN32/releases/download/2.9.1/pthreads-win32-2.9.1_%ARCH%.zip
  - cmd: 7z -y x pthreads-win32-2.9.1_%ARCH%.zip -oC:\projects\pthreads-win32\
  - cmd: cd "C:\projects\"
  # Build jpeg-turbo
  # Install nasm
  - appveyor DownloadFile %NASM_DOWNLOAD_LINK% -FileName nasm.exe
  - cmd: nasm.exe /S /v/qn
  # Get libjpeg-turbo
  - appveyor DownloadFile https://github.com/libjpeg-turbo/libjpeg-turbo/archive/refs/tags/%JPEG_VERSION%.zip -FileName libjpeg-turbo.zip
  - cmd: 7z -y x libjpeg-turbo.zip -oC:\projects\
  - cmd: cd "C:\projects\libjpeg-turbo-%JPEG_VERSION%"
  - cmd: md build
  - cmd: cd "C:\projects\cppTango"

install:
  #copy tree for debug build
  - cmd: cd c:/projects/
  # in case of wrong directory for cloning
  - cmd: rename %APPVEYOR_BUILD_FOLDER% cppTango
  # Setting Visual Compiler
  - cmd: cd "C:\projects\"
  - cmd: if %ARCH%==win32-msvc15 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmd: if %ARCH%==x64-msvc15 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: echo "Generator='%CMAKE_GENERATOR%'"
  - cmd: echo "Platform='%Platform%'"
  - cmd: set PYTHONPATH=%PYTHONPATH%
  - cmd: set PATH=%PYTHONPATH%;%PATH%
  # Libjpeg-turbo
  - cmd: cd "C:\projects\libjpeg-turbo-%JPEG_VERSION%\build"
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DWITH_TURBOJPEG=ON -DCMAKE_INSTALL_PREFIX="%TANGO_JPEG_BASE%" -DCMAKE_DEBUG_POSTFIX=d ..
  - cmd: cmake --build ./ --target install --config %CONFIGURATION%
  # Tango IDL
  - cmd: cd %IDL_SOURCE%
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX="%TANGO_IDL_BASE%" .
  - cmd: cmake --build ./ --target install --config %CONFIGURATION%
  # Tango API
  - cmd: cd "C:\projects\cppTango"
  - cmd: set TANGO_ZMQ_BASE=C:/projects/zeromq/
  - cmd: set TANGO_CPPZMQ_BASE=C:/projects/zeromq/
  - cmd: set TANGO_OMNI_BASE=C:/projects/omniorb/
  - cmd: set PTHREAD_WIN=C:/projects/pthreads-win32/
  - cmd: if not defined TANGO_USE_PCH set TANGO_USE_PCH=OFF
  - cmd: set TANGO_WARNINGS_AS_ERRORS=%TANGO_WARNINGS_AS_ERRORS%
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -DTANGO_WARNINGS_AS_ERRORS=%TANGO_WARNINGS_AS_ERRORS% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_CXX_FLAGS_RELEASE="%CMAKE_CXX_FLAGS_RELEASE%" -DCMAKE_CXX_FLAGS_DEBUG="%CMAKE_CXX_FLAGS_DEBUG%" -DTANGO_IDL_BASE="%TANGO_IDL_BASE%" -DTANGO_OMNI_BASE="%TANGO_OMNI_BASE%" -DTANGO_ZMQ_BASE="%TANGO_ZMQ_BASE%" -DTANGO_CPPZMQ_BASE="%TANGO_CPPZMQ_BASE%" -DTANGO_JPEG_BASE="%TANGO_JPEG_BASE%%JPEG_ARCH%" -DPTHREAD_WIN=%PTHREAD_WIN% -DTANGO_USE_PCH=OFF -DTANGO_USE_JPEG=ON -DJPEG_DEBUG_POSTFIX=d -DBUILD_TESTING=OFF -DTANGO_INSTALL_DEPENDENCIES=ON ..

clone_folder: C:/projects/cppTango

build_script:
  - cmd: cd C:/projects/cppTango/build
  - cmd: cmake --build . --config %CONFIGURATION%

after_build:
  - cmd: set /p TANGO_LIB_VER=<VERSION
  - cmd: echo %TANGO_LIB_VER%
  - cmd: cd C:/projects/cppTango/build
  - cmd: cpack -C %CONFIGURATION% -G WIX
  - cmd: cpack -C %CONFIGURATION% -G ZIP

on_finish:
  #RDP for finish
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_failure:
  #RDP for failure
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: build/*.zip
  - path: build/*.msi
