/*----- PROTECTED REGION ID(DummyClassStateMachine.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        DummyClassStateMachine.cpp
//
// description : State machine file for the DummyClass class
//
//
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "DummyClass.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DummyClass::DummyClassStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace DummyClass_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(DummyClass::DummyClassStateAllowed.AdditionalMethods) ENABLED START -----*/
/* clang-format on */
//	Additional Methods
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DummyClass::DummyClassStateAllowed.AdditionalMethods

}	//	End of namespace
